// Provider registry — compiled from awesome-freellm-apis (freellm.net).
// All providers expose an OpenAI-compatible endpoint unless marked "anthropic".

export type ProviderApi = "openai" | "anthropic";

export interface ProviderPreset {
  id: string;
  name: string;
  baseUrl: string; // OpenAI-compatible base URL (may contain {account_id})
  keyUrl: string; // where the user can obtain an API key
  api: ProviderApi;
  free: boolean; // has a permanent free tier
  requiresKey: boolean;
  needsAccountId?: boolean;
  note?: string;
  color: string; // brand dot color
  defaultModels: string[];
}

export interface CustomProvider {
  id: string; // "custom-<ts>"
  name: string;
  baseUrl: string;
  requiresKey: boolean;
  defaultModels: string[];
}

export type AnyProvider =
  | ({ kind: "preset" } & ProviderPreset)
  | ({ kind: "custom" } & Omit<CustomProvider, never>);

export interface ChatMessage {
  role: "user" | "assistant" | "system";
  content: string;
}

export const PROVIDERS: ProviderPreset[] = [
  {
    id: "groq",
    name: "Groq",
    baseUrl: "https://api.groq.com/openai/v1",
    keyUrl: "https://console.groq.com/keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Blazing fast LPU inference · free, no credit card",
    color: "#F55036",
    defaultModels: [
      "llama-3.3-70b-versatile",
      "moonshotai/kimi-k2-instruct",
      "openai/gpt-oss-120b",
      "qwen/qwen3-32b",
      "groq/compound",
      "meta-llama/llama-4-scout-17b-16e-instruct",
    ],
  },
  {
    id: "google",
    name: "Google Gemini",
    baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai",
    keyUrl: "https://aistudio.google.com/app/apikey",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "1M context · free, no credit card",
    color: "#4285F4",
    defaultModels: ["gemini-3-flash", "gemini-2.5-flash", "gemini-2.5-pro", "gemini-3-pro"],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    baseUrl: "https://openrouter.ai/api/v1",
    keyUrl: "https://openrouter.ai/workspaces/default/keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "One key, 400+ models · free tier + paid",
    color: "#8B5CF6",
    defaultModels: [
      "nvidia/nemotron-3-ultra-550b-a55b:free",
      "deepseek/deepseek-chat-v3.1:free",
      "meta-llama/llama-3.3-70b-instruct:free",
      "google/gemini-2.5-flash:free",
      "moonshotai/kimi-k2:free",
      "anthropic/claude-sonnet-4.5",
      "openai/gpt-5.2",
    ],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    baseUrl: "https://api.mistral.ai/v1",
    keyUrl: "https://console.mistral.ai/api-keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free experiment tier · La Plateforme",
    color: "#FF7000",
    defaultModels: [
      "mistral-large-latest",
      "mistral-medium-latest",
      "mistral-small-latest",
      "open-mistral-nemo",
      "codestral-latest",
    ],
  },
  {
    id: "cerebras",
    name: "Cerebras",
    baseUrl: "https://api.cerebras.ai/v1",
    keyUrl: "https://cloud.cerebras.ai/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Wafer-scale speed · free tier",
    color: "#7C3AED",
    defaultModels: ["llama3.1-70b", "llama3.1-8b", "gpt-oss-120b", "qwen-3-235b-a22b-instruct-2507"],
  },
  {
    id: "github",
    name: "GitHub Models",
    baseUrl: "https://models.github.ai/inference",
    keyUrl: "https://github.com/settings/personal-access-tokens/new",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free with a GitHub token",
    color: "#E6EDF3",
    defaultModels: [
      "openai/gpt-5-mini",
      "openai/gpt-4.1",
      "microsoft/Phi-4",
      "meta/Llama-4-Maverick-17B-128E-Instruct-FP8",
      "deepseek/DeepSeek-V3.2",
      "mistral-ai/Mistral-Large-2411",
    ],
  },
  {
    id: "huggingface",
    name: "Hugging Face",
    baseUrl: "https://router.huggingface.co/v1",
    keyUrl: "https://huggingface.co/settings/tokens",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free monthly credits on the router",
    color: "#FFB000",
    defaultModels: [
      "meta-llama/Llama-3.3-70B-Instruct",
      "Qwen/Qwen3-32B",
      "deepseek-ai/DeepSeek-V3.2",
      "google/gemma-3-27b-it",
    ],
  },
  {
    id: "cohere",
    name: "Cohere",
    baseUrl: "https://api.cohere.ai/compatibility/v1",
    keyUrl: "https://dashboard.cohere.com/api-keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Trial keys are free · 20 RPM",
    color: "#39594D",
    defaultModels: ["command-a-111b", "command-a-plus-08-2024", "command-r-plus", "command-r"],
  },
  {
    id: "nvidia",
    name: "NVIDIA NIM",
    baseUrl: "https://integrate.api.nvidia.com/v1",
    keyUrl: "https://build.nvidia.com/settings/api-keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "128+ free models · phone verification",
    color: "#76B900",
    defaultModels: [
      "z-ai/glm-5.2",
      "moonshotai/kimi-k2.6",
      "meta/llama-3.3-70b-instruct",
      "deepseek-ai/deepseek-v3.2",
      "nvidia/llama-3.1-nemotron-70b-instruct",
    ],
  },
  {
    id: "sambanova",
    name: "SambaNova",
    baseUrl: "https://api.sambanova.ai/v1",
    keyUrl: "https://cloud.sambanova.ai/apis",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free tier with RDU speed",
    color: "#F2762E",
    defaultModels: [
      "Meta-Llama-3.3-70B-Instruct",
      "DeepSeek-V3.1",
      "DeepSeek-V3.2",
      "Llama-4-Maverick-17B-128E-Instruct",
    ],
  },
  {
    id: "zhipu",
    name: "Z AI (Zhipu)",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    keyUrl: "https://open.bigmodel.cn/usercenter/apikeys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "GLM Flash models are free",
    color: "#4F6BFE",
    defaultModels: ["glm-4.7-flash", "glm-4.5-flash", "glm-5", "glm-4.6v-flash"],
  },
  {
    id: "llm7",
    name: "LLM7.io",
    baseUrl: "https://api.llm7.io/v1",
    keyUrl: "https://token.llm7.io",
    api: "openai",
    free: true,
    requiresKey: false,
    note: "Works instantly — no key needed",
    color: "#00C2A8",
    defaultModels: ["gpt-5-mini", "gpt-oss-20b", "mistral-Nemo-Instruct-2407", "deepseek-v3.2"],
  },
  {
    id: "cloudflare",
    name: "Cloudflare Workers AI",
    baseUrl: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens",
    api: "openai",
    free: true,
    requiresKey: true,
    needsAccountId: true,
    note: "10K free neurons/day · needs account ID",
    color: "#F6821F",
    defaultModels: [
      "@cf/meta/llama-3.3-70b-instruct-fp8-fast",
      "@cf/qwen/qwen3-30b-a3b-fp8",
      "@cf/mistral/mistral-7b-instruct-v0.1",
    ],
  },
  {
    id: "modelscope",
    name: "ModelScope",
    baseUrl: "https://api-inference.modelscope.cn/v1",
    keyUrl: "https://modelscope.cn/my/myaccesstoken",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "57 free models · 2,000 req/day",
    color: "#6C5CE7",
    defaultModels: ["Qwen/Qwen3.5-35B-A3B", "MiniMax/MiniMax-M2.5", "deepseek-ai/DeepSeek-V3.2"],
  },
  {
    id: "opencode",
    name: "OpenCode Zen",
    baseUrl: "https://opencode.ai/zen/v1",
    keyUrl: "https://opencode.ai/auth",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Curated free models from OpenCode",
    color: "#F8FAFC",
    defaultModels: ["big-pickle", "deepseek-v4-flash-free", "mimo-v2.5-free"],
  },
  {
    id: "ovhcloud",
    name: "OVHcloud AI",
    baseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    keyUrl: "https://www.ovhcloud.com/en/public-cloud/ai-endpoints/catalog/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free endpoints · EU hosted",
    color: "#0050D7",
    defaultModels: ["Meta-Llama-3_3-70B-Instruct", "Qwen3.5-397B-A17B", "Qwen3.6-27B"],
  },
  {
    id: "kilocode",
    name: "Kilo Code",
    baseUrl: "https://api.kilo.ai/api/gateway",
    keyUrl: "https://app.kilo.ai/profile",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free coding gateway · 200 req/hr",
    color: "#22D3EE",
    defaultModels: [
      "nvidia/nemotron-3-ultra-550b-a55b:free",
      "stepfun/step-3.7-flash:free",
      "nvidia/nemotron-3-super-120b-a12b:free",
    ],
  },
  {
    id: "ollama-cloud",
    name: "Ollama Cloud",
    baseUrl: "https://ollama.com/v1",
    keyUrl: "https://ollama.com/settings/keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free cloud tier from Ollama",
    color: "#FFFFFF",
    defaultModels: ["deepseek-v4-flash", "gpt-oss:120b-cloud", "minimax-m3", "qwen3.5"],
  },
  {
    id: "agnes",
    name: "Agnes AI",
    baseUrl: "https://apihub.agnes-ai.com/v1",
    keyUrl: "https://platform.agnes-ai.com/settings/apiKeys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free 30 RPM tier",
    color: "#F472B6",
    defaultModels: ["agnes-2.0-flash", "agnes-1.5-flash"],
  },
  {
    id: "aion",
    name: "Aion Labs",
    baseUrl: "https://api.aionlabs.ai/v1",
    keyUrl: "https://www.aionlabs.ai/app/api-keys/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free 15 RPM tier",
    color: "#818CF8",
    defaultModels: ["aion-labs/aion-3.0", "aion-labs/aion-2.0", "aion-labs/aion-rp-llama-3.1-8b"],
  },
  {
    id: "alibaba",
    name: "Alibaba Model Studio",
    baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    keyUrl: "https://bailian.console.alibabacloud.com/?apiKey=1",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Qwen models · free quota",
    color: "#FF6A00",
    defaultModels: ["qwen3-max", "qwen3-plus", "qwen3-vl-plus"],
  },
  {
    id: "siliconflow",
    name: "SiliconFlow",
    baseUrl: "https://api.siliconflow.cn/v1",
    keyUrl: "https://cloud.siliconflow.cn/account/ak",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free small models",
    color: "#7DD3FC",
    defaultModels: [
      "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
      "Qwen/Qwen2.5-7B-Instruct",
      "deepseek-ai/DeepSeek-V3.2",
    ],
  },
  {
    id: "chutes",
    name: "Chutes.ai",
    baseUrl: "https://llm.chutes.ai/v1",
    keyUrl: "https://chutes.ai/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Community-powered free models",
    color: "#A3E635",
    defaultModels: ["deepseek-ai/DeepSeek-R1", "meta-llama/Meta-Llama-3.1-70B-Instruct"],
  },
  {
    id: "glhf",
    name: "Glhf.chat",
    baseUrl: "https://glhf.chat/api/openai/v1",
    keyUrl: "https://glhf.chat/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Unlimited for free models",
    color: "#34D399",
    defaultModels: ["hf:meta-llama/Meta-Llama-3.1-70B-Instruct", "hf:mistralai/Mixtral-8x7B-Instruct-v0.1"],
  },
  {
    id: "nscale",
    name: "Nscale",
    baseUrl: "https://inference.api.nscale.com/v1",
    keyUrl: "https://console.nscale.com/",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Fair-use free tier",
    color: "#FB923C",
    defaultModels: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"],
  },
  {
    id: "nebius",
    name: "Nebius AI",
    baseUrl: "https://api.studio.nebius.com/v1",
    keyUrl: "https://studio.nebius.com/settings/api-keys",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free tier-based quota",
    color: "#C084FC",
    defaultModels: ["Qwen/Qwen3-235B-A22B", "meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3.2"],
  },
  {
    id: "ai21",
    name: "AI21 Labs",
    baseUrl: "https://api.ai21.com/studio/v1",
    keyUrl: "https://studio.ai21.com/account/api-key",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Jamba models · trial keys",
    color: "#FDBA74",
    defaultModels: ["jamba-large-1.7", "jamba-mini-2"],
  },
  {
    id: "xai",
    name: "xAI (Grok)",
    baseUrl: "https://api.x.ai/v1",
    keyUrl: "https://console.x.ai",
    api: "openai",
    free: true,
    requiresKey: true,
    note: "Free monthly credits",
    color: "#E7E9EA",
    defaultModels: ["grok-4.1-fast", "grok-4.3", "grok-3-mini"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com/v1",
    keyUrl: "https://platform.deepseek.com/api_keys",
    api: "openai",
    free: false,
    requiresKey: true,
    note: "Ultra-cheap paid API",
    color: "#4D6BFE",
    defaultModels: ["deepseek-chat", "deepseek-reasoner"],
  },
  {
    id: "openai",
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    keyUrl: "https://platform.openai.com/api-keys",
    api: "openai",
    free: false,
    requiresKey: true,
    note: "GPT flagship models · paid",
    color: "#10A37F",
    defaultModels: ["gpt-5.2", "gpt-5-mini", "gpt-4.1", "o4-mini"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    baseUrl: "https://api.anthropic.com",
    keyUrl: "https://console.anthropic.com/settings/keys",
    api: "anthropic",
    free: false,
    requiresKey: true,
    note: "Claude models · paid · native API",
    color: "#D97757",
    defaultModels: [
      "claude-sonnet-4-5-20250929",
      "claude-opus-4-5-20251101",
      "claude-haiku-4-5-20251001",
    ],
  },
  {
    id: "ollama-local",
    name: "Ollama (Local)",
    baseUrl: "http://localhost:11434/v1",
    keyUrl: "https://ollama.com/download",
    api: "openai",
    free: true,
    requiresKey: false,
    note: "Runs on your machine · 100% private",
    color: "#D1D5DB",
    defaultModels: ["llama3.3", "qwen3", "deepseek-r1", "mistral"],
  },
];

export const MODES: Record<
  string,
  { id: string; label: string; icon: string; prompt: string }
> = {
  chat: {
    id: "chat",
    label: "Chat",
    icon: "MessageSquare",
    prompt:
      "You are Rawchat — a sharp, warm, and honest AI assistant. Be concise by default, expand when asked. Use Markdown formatting (headings, lists, tables, code blocks) whenever it improves clarity. Never invent facts.",
  },
  code: {
    id: "code",
    label: "Code",
    icon: "Code2",
    prompt:
      "You are Rawchat Code — an elite pair-programmer. Write complete, runnable, production-quality code with zero placeholders. When the user asks for a web UI, page, or app, respond with ONE complete self-contained HTML file inside a single ```html code block (inline CSS/JS, Tailwind via CDN allowed) so it can be previewed live. Explain decisions briefly in Markdown around the code.",
  },
  write: {
    id: "write",
    label: "Write",
    icon: "PenLine",
    prompt:
      "You are Rawchat Writer — a world-class writing partner. Match the requested tone precisely, favour vivid concrete language over clichés, and structure long pieces with Markdown headings.",
  },
  brainstorm: {
    id: "brainstorm",
    label: "Ideate",
    icon: "Lightbulb",
    prompt:
      "You are Rawchat Spark — a relentless creativity engine. Generate many diverse angles, combine unexpected ideas, and challenge assumptions. Use tight Markdown lists.",
  },
};

export function getProvider(id: string): ProviderPreset | undefined {
  return PROVIDERS.find((p) => p.id === id);
}
